//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiningPlantConsole.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentMaterials
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public int SupplierID { get; set; }
        public decimal Cost { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> UsedInOrderID { get; set; }
        public Nullable<int> UsedInContractID { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual MilitaryContracts MilitaryContracts { get; set; }
    }
}
