//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiningPlantConsole.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxes
    {
        public int TaxID { get; set; }
        public string TaxType { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ContractID { get; set; }
        public Nullable<int> ProgramID { get; set; }
    
        public virtual MilitaryContracts MilitaryContracts { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual SocialPrograms SocialPrograms { get; set; }
    }
}
